### ISSUE TITLE
Google blocks code after certain number of requests

### ISSUE THREAD

**Issue by cklaassen** [bandsquad/google-trends-fetch#18]

**Comment by cklaassen** [comment]
<img width="568" alt="screen shot 2018-01-02 at 2 14 00 pm" src="https://user-images.githubusercontent.com/20288439/34502185-4109a7c2-efc7-11e7-868d-37b10fba7c42.png">

**Comment by nathanparekh** [comment]
![screen shot 2018-01-05 at 5 26 35 pm](https://user-images.githubusercontent.com/33500247/34634914-c2d634b4-f23d-11e7-98a9-c5c705aa2197.jpg)

We can catch it in an exception by using `import python as pt` and then catching `pt.exceptions.ResponseError`

**Comment by nathanparekh** [comment]
Update on `CSV-googleBypass-fetch`
- Basic system is the same as before, except with a descriptive filename
- Will save to CSV as did before... after error retries will simply break
- **Need to add solution to resume from an existing CSV**
