### ISSUE TITLE
Returns NaN until it changes the max root

### ISSUE THREAD

**Issue by nathanparekh** [bandsquad/google-trends-fetch#24]
No matter how it is set in new-import, it returns columns of NaN until it finds a new max (which is weird if everything returns NaN)

**Comment by nathanparekh** [comment]
Potentially relevant StackOverflow thread: [https://stackoverflow.com/questions/40339886/pandas-concat-generates-nan-values](https://stackoverflow.com/questions/40339886/pandas-concat-generates-nan-values)

**Comment by cklaassen** [comment]
Potentially relevant StackOverflow thread #2: https://stackoverflow.com/questions/37408972/python-pandas-cannot-merge-multiple-dataframe-returning-nan

**Comment by cklaassen** [comment]
Potentially relevant research source: http://chris.friedline.net/2015-12-15-rutgers/lessons/python2/04-merging-data.html

**Comment by nathanparekh** [comment]
I think that this might be the best solution, if it is actually applicable: [https://stackoverflow.com/questions/46754398/pandas-merge-returns-nan](https://stackoverflow.com/questions/46754398/pandas-merge-returns-nan)

**Comment by cklaassen** [comment]
The one problem with what we are running into right now is the way that you set up the merge.  It looks like that stackoverflow forum is reffering to the .merge() ability that pandas can do, and we do not have our code set up that way.

**Comment by nathanparekh** [comment]
It should all be related though, right?
I could open another StackOverflow thread with a more specific question...

**Comment by nathanparekh** [comment]
This looks like a perfect match:
https://stackoverflow.com/questions/30269474/populating-a-dataframe-column-in-pandas-with-another-dataframes-column
