### ISSUE TITLE
Add colored text for output

### ISSUE THREAD

**Issue by HeinTimothy** [bandsquad/google-trends-fetch#30]
Increase: Green
Within margin: Black
Decrease: Red

**Comment by cklaassen** [comment]
https://pypi.python.org/pypi/colorama

There is a thing called colorama which may work for this

**Comment by HeinTimothy** [comment]
I figured out colorama but it broke fetch for some reason

**Comment by HeinTimothy** [comment]
I figured it out, note that print(num) doesn't convert num to a string, it just takes it as an int so you can't color it directly

**Comment by nathanparekh** [comment]
You can just use `str()` to convert.

**Comment by nathanparekh** [comment]
Seriously though... let's do this later. Or maybe never at all. This really isn't necessary.
