### ISSUE TITLE
Program gets stuck repeating same results

### ISSUE THREAD

**Issue by cklaassen** [bandsquad/google-trends-fetch#32]
[-.txt](https://github.com/bandsquad/google-trends-fetch/files/1657286/-.txt)

**Comment by nathanparekh** [comment]
@cklaassen You should take a look at catching other errors in the try-except statement. Of course, we need KeyboardInterrupt to work, so take a look at this:
[https://stackoverflow.com/questions/26199208/try-and-except-catch-all-errors-except-for-sys-exit](https://stackoverflow.com/questions/26199208/try-and-except-catch-all-errors-except-for-sys-exit)

**Comment by cklaassen** [comment]
This problem could be due to those lines of code you found out i forgot yesterday, because I have repeatedly run this program and it hasn't happened since.

**Comment by cklaassen** [comment]
Ok, turns out it is still doing it just not as frequently.

It normally happens before a new max is set but it also sometimes randomly happens in the code.

**Comment by cklaassen** [comment]
I know what is happening now, I will show you guys at lunch, it should be a pretty easy fix.
