### ISSUE TITLE
Find a way to save the max so that the program doesn't waste time re-analyzing data

### ISSUE THREAD

**Issue by cklaassen** [bandsquad/google-trends-fetch#37]
Right now our program has to repeat several times due to the max search changing.  I think if we find a way to save the max search but still look through the items to make sure that none are greater it could improve how many terms we can search before google locks us out.

**Comment by nathanparekh** [comment]
That's not practical. Theoretically, it does save the max (by putting it in the first column) when it saves to `result-partial.csv`. There's no way to compare for the max without doing a full search, so this is the best way to do it.
