### ISSUE TITLE
The program restarts after confirming input for continuing

### ISSUE THREAD

**Issue by cklaassen** [bandsquad/google-trends-fetch#69]
After running the program for the second time, it doesn't continue where it left of, it just started over

**Comment by cklaassen** [comment]
I looked through our whole fetch code and couldn't find anything that would do this.  Could you check your code and see if It does the same thing?  If not you might have forgotten to push something.

**Comment by nathanparekh** [comment]
Running debugger on `master` at line 16... `results` contains 15 company values but only contains series values for 11... the four that are missing are the ones that have two word values

**Comment by nathanparekh** [comment]
The new `fix-imports` branch contains a change that prevents it from restarting using UGG, but instead it just skips everything. This may have been the main problem all along.

TO TEST:
- [ ] Check if when it restarts on `master` it restarts from UGG and then to the beginning or if it goes to UGG and then jumps to the end of what was already completed

**Comment by nathanparekh** [comment]
Update: it **is** skipping all the terms in `completed` entirely.

**Comment by cklaassen** [comment]
This was in fetch.py which we have stopped using, so not an issue anymore
