### ISSUE TITLE
Compare outlier results with other dataframes to search for a trend

### ISSUE THREAD

**Issue by cklaassen** [bandsquad/google-trends-fetch#77]
If all of the companies have outliers on the same day, throw an error message to notify, clearly shouldn't happen

**Comment by nathanparekh** [comment]
That could happen sometimes, if some shoe thing happens all at once for a whole bunch of different brands (some sports event?), is useful to know. However, it doesn't have to be an _error_, because it doesn't have to be _wrong_.

**Comment by cklaassen** [comment]
what I meant by error is something to notify us, (error message seemed like the easiest option in python because of the red text)

**Comment by cklaassen** [comment]
Not really something we need to do
